services:
  lambda-rie:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "9000:8080"
    environment:
      - AWS_REGION=us-east-1
      # - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      # - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      # - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      # - S3_BUCKET=your-test-bucket
      # - S3_PREFIX=your-test-prefix
      # - RES_BUCKET=your-result-bucket
      # - ETL_OBJECT_TABLE=your-etl-table
      # - OPERATION_TYPE=extract_only
    command: ["main.lambda_handler"]