version: '3.8'

services:
  job-service:
    build: .
    ports:
      - "8001:8000"
    environment:
      # AWS Configuration
      - AWS_REGION=us-east-1
      # - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-your-access-key}
      # - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-your-secret-key}
      # - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:-}
    volumes:
      - ./data:/app/data
      - /tmp:/tmp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: job-service-network